name: Javadoc CI

on:
  push:
    branches:
      - master

permissions: 
  contents: write
jobs:
  javadoc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        CLEAN: false
        FOLDER: item-nbt-api/target/apidocs
        target-folder: v2-api
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        CLEAN: false
        FOLDER: item-nbt-plugin/target/apidocs
        target-folder: v2-plugin